Added exclusion param for projects
dynatrace-oss/dynatrace-gcp-monitor pull request #428
Opened 2023-08-16 08:13 UTC by joaquinfilipic-dynatrace

2023-08-16 11:39 UTC, dtwwolinski requested changes

2023-08-16 11:39 UTC, dtwwolinski commented on src/main.py
> +        disabled_projects.extend(filter(None, config.excluded_projects().split(',')))
Imho it should be set

2023-08-17 09:20 UTC, dtwwolinski approved these changes

2023-08-17 09:50 UTC, nikita-paskal-dynatrace approved these changes

2023-08-17 10:02 UTC, merged