PCLOUDS-4015 - service logs schemas
dynatrace-oss/dynatrace-gcp-monitor pull request #504
Opened 2024-04-08 14:56 UTC by nikita-paskal-dynatrace

2024-04-23 09:21 UTC, szymon-nagel-dt requested changes

2024-04-23 09:21 UTC, szymon-nagel-dt commented on src/config_logs/google-data-transfer/googlge-data-transfer.json
> +{}
Why you didn't add a storage_transfer_job entity log linking despite avilable logs in GPC?
![image](https://github.com/dynatrace-oss/dynatrace-gcp-monitor/assets/138470854/f5992639-dc3f-425a-a106-a1d2ef975472)

2024-04-26 09:08 UTC, nikita-paskal-dynatrace commented on src/config_logs/google-hybrid-connectivity/google-hybrid-connectivity.json
> +{}
won't do, nothing to add

2024-04-29 14:23 UTC, szymon-nagel-dt approved these changes
Besides changes mentioned Looks good to me :)

2024-04-29 14:23 UTC, szymon-nagel-dt commented on src/config_logs/google-hybrid-connectivity/google-hybrid-connectivity.json
> +{}
Can delete this empty file then

2024-04-29 14:23 UTC, szymon-nagel-dt commented on src/config_logs/google-datastore/google-datastore-database.json
> +{
Again , the same as above but leave as it is

2024-04-29 14:23 UTC, szymon-nagel-dt commented on src/config_logs/google-datastore/google-datastore-index.json
> +{
I think this can be deleted

2024-05-06 14:30 UTC, szymon-nagel-dt approved these changes

2024-05-06 14:35 UTC, merged